name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'nightly'
        type: choice
        options:
        - nightly
        - "%date"
  push:
    tags:
    - '*'

env:
  KICK_VERSION: "%{git.tag} || ${{github.event.inputs.version}} || nightly"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fedora:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora: ["43"]
    container:
      image: fedora:${{matrix.fedora}}
    steps:
    - run: cat /etc/fedora-release
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: dnf install --assumeyes gcc git
    - uses: udoprog/kick@nightly
    - run: kick define --github-action
      id: release
    - run: cargo build --release -p wolo
    - run: kick rpm --append f${{matrix.fedora}} --output dist
    - uses: actions/upload-artifact@v4
      with:
        name: dist-fedora-${{matrix.fedora}}
        path: dist

  publish:
    permissions: write-all
    needs: [fedora]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with: {pattern: "dist-*", merge-multiple: true, path: dist}
    - uses: udoprog/kick@nightly
    - run: kick gh release --github-action --upload "dist/*"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
